# Highly Divisible Triangular Number
# Problem 12

# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1+2+3+4+5+6+7 = 28
# The first ten terms would be: 1,3,6,10,15,21,28,36,45,55,...

# Let us list the factors of the first seven triangle numbers:
# What is the value of the first triangle number to have over five hundred divisors?

from functools import reduce
from python.exercise20_PrimesMultiples import multiples


# triangle number = n(n+1) / 2
def triangle_numbers(number: int) -> int:
    """Return the n-th triangle number.

    A triangle number represents the total number of dots that can form
    an equilateral triangle. It is calculated using the formula:
    ``T_n = n(n + 1) / 2``.

    Args:
        number (int): The position of the triangle number to calculate.

    Returns:
        int: The n-th triangle number.

    Example:
        >>> triangle_numbers(7)
        28
    """
    return (number * (number + 1)) // 2

def len_divisors(number: int) -> int:
    """Return the total number of divisors of a given integer.

    The number of divisors of a number is obtained by prime factorization.
    For a number ``n = p1^a * p2^b * ... * pk^z``, the total number of divisors is:
    ``(a + 1)(b + 1)...(z + 1)``.

    Args:
        number (int): The number for which the divisor count will be computed.

    Returns:
        int: The number of divisors of the input number.

    Example:
        >>> len_divisors(12)
        6
        # because 12 = 2² x 3¹ → (2 + 1)(1 + 1) = 6
    """
    multiples_number = multiples(number)
    count_exp = [
        (multiples_number.count(primes) + 1) for primes in set(multiples_number)
    ]

    return reduce(lambda x, y: x * y, count_exp,1)

# What is the value of the first triangle number to have over five hundred divisors?
def len_div_triangle(min_div: int) -> int:
    """Return the first triangle number with at least `min_div` divisors.

    The function incrementally generates triangle numbers starting from 1
    and checks their number of divisors until finding one that meets
    or exceeds the given threshold.

    Args:
        min_div (int): Minimum number of divisors required.

    Returns:
        int: The first triangle number with at least `min_div` divisors.

    Example:
        >>> len_div_triangle(6)
        28
        # 28 has 6 divisors
    """
    n = 1
    triangle = triangle_numbers(n)

    while len_divisors(triangle) < min_div:
        n += 1
        triangle = triangle_numbers(n)

    return triangle


def len_div_triangle_number(len_div: int) -> int:
    """Return the first triangle number with at least `len_div` divisors using an optimized method.

    This function uses the property that:
    - If `n` is even: divisors(Tn) = divisors(n/2) x divisors(n+1)
    - If `n` is odd:  divisors(Tn) = divisors(n) x divisors((n+1)/2)

    This avoids computing the prime factorization of the triangle number directly,
    making the search much faster.

    Args:
        len_div (int): Minimum number of divisors required.

    Returns:
        int: The first triangle number with at least `len_div` divisors.

    Example:
        >>> len_div_triangle_number(6)
        28
        # 28 has 6 divisors
    """
    n = 1
    divisors = 0

    while divisors < len_div:
        n += 1
        if n % 2 == 0:
            divisors = len_divisors(n // 2) * len_divisors(n + 1)
        else:
            divisors = len_divisors(n) * len_divisors((n + 1) // 2)

    return n * (n + 1) // 2
